#pragma once

#include "orderbook/types.hpp"
#include "orderbook/order_book.hpp"

#include <vector>
#include <functional>

namespace orderbook {

// ──────────────────────────────────────────────
// Events produced by the matching engine
// ──────────────────────────────────────────────

/// A trade that occurred when two orders matched.
struct Trade {
    OrderId   buy_order_id;
    OrderId   sell_order_id;
    Price     price;       // Execution price (resting order's price)
    Quantity  quantity;     // Quantity traded
    Timestamp timestamp;
};

/// Collection of all events produced by processing a single incoming order.
struct MatchResult {
    /// The order that was submitted.
    OrderId order_id{0};

    /// Trades generated by this order (may be 0 or more).
    std::vector<Trade> trades;

    /// Total quantity that was filled.
    Quantity filled_quantity{0};

    /// True if the order is now resting in the book (unfilled remainder).
    bool is_resting{false};

    /// True if the order was fully filled.
    bool is_fully_filled{false};

    /// True if the order was cancelled (IOC/FOK with no/partial fill,
    /// or market order with no liquidity).
    bool is_cancelled{false};
};

/// The matching engine processes incoming orders against an order book
/// using price-time priority.
///
/// How matching works:
///   1. A new buy order checks the ask side. If the buy price >= best ask,
///      it matches against resting sell orders starting from the lowest ask.
///   2. Within each price level, orders are matched in FIFO order (time priority).
///   3. Each match produces a Trade at the resting order's price (price improvement
///      for the aggressor — a buy at $11 hitting an ask at $10 trades at $10).
///   4. Fully filled resting orders are removed from the book.
///   5. Any unfilled remainder of the incoming order is rested in the book
///      (for Limit orders) or cancelled (for Market/IOC).
///
/// Supported order types:
///   - Limit:  Match what you can, rest the remainder.
///   - Market: Match what you can, cancel the remainder (no resting).
///   - IOC:    Same as Market — match aggressively, cancel unfilled.
///   - FOK:    Only execute if the ENTIRE quantity can be filled. Otherwise cancel.
///
/// Design: single-threaded. Real exchanges (CME, NASDAQ) also use single-threaded
/// matching per instrument — parallelism happens across instruments, not within.
class MatchingEngine {
public:
    MatchingEngine() = default;

    // Non-copyable (owns an OrderBook)
    MatchingEngine(const MatchingEngine&) = delete;
    MatchingEngine& operator=(const MatchingEngine&) = delete;

    /// Submit an order to the matching engine.
    /// The engine will attempt to match it against the opposite side,
    /// and rest or cancel the remainder based on order type.
    ///
    /// The caller retains ownership of the Order memory.
    /// The Order's fields (filled_quantity, status) will be updated.
    MatchResult submit_order(Order* order);

    /// Cancel a resting order by ID.
    /// Returns true if the order was found and cancelled.
    bool cancel_order(OrderId order_id);

    /// Read-only access to the underlying order book.
    [[nodiscard]] const OrderBook& book() const noexcept { return book_; }

    /// Mutable access (for testing and queries that need non-const methods).
    [[nodiscard]] OrderBook& book() noexcept { return book_; }

private:
    OrderBook book_;

    /// Attempt to match an incoming buy order against the ask side.
    void match_buy(Order* order, MatchResult& result);

    /// Attempt to match an incoming sell order against the bid side.
    void match_sell(Order* order, MatchResult& result);

    /// Check if a FOK order can be fully filled before executing.
    [[nodiscard]] bool can_fill_completely(const Order* order) const;
};

} // namespace orderbook
